name: End to End Tests with Puppeteer

on: [push] # the Github Action will activate "on" the event that you "push" to the repo

jobs:
  tests: # the name of the status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clear Node Modules and Cache
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm cache clean --force
      
      - name: Install Dependencies
        run: |
          npm install
          npm install --save-dev babel-jest @babel/core @babel/preset-env puppeteer jest-puppeteer

      - name: Jest with Puppeteer
        run: npm run test

      
