name: End to End Tests with Puppeteer

on: [push] # the Github Action will activate "on" the event that you "push" to the repo

jobs:
  tests: # the name of the status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install

      - name: Jest Setup
        run: npm install jest
      - name: Puppeteer Setup
        run: npm install puppeteer
      - name: Jest with Puppeteer
        run: npm run test
